####**The challenge** -- Use a pre-trained ResNet-18 model and implement a custom reduction operator in ONNX C++ to perform image similarity on the given dataset


* what is deformable network
* what is ONNX and how to use it, why c++ with ONNX
* what is output maps in CNN.


TODO:

* Create a model called ReductionResNET-18 -> can use pretrained from torchvison.
* what is reduction operator the C++ part
* 

MY APPROACH :

First i will read about the resnet-18 architechture what it is made of.
than we will take a simple resnet-18 model. and perform transfer learning on given data set.



RESEARCH:

Link: https://medium.com/swlh/5-pytorch-functions-for-reduction-operations-b25aa1e208a3
https://shuzhanfan.github.io/2018/11/ResNet/
deformable convolution networks
https://arxiv.org/abs/1703.06211
extract featrues from intermediate layers of pytroch pretrained resnet-18 model

https://medium.com/the-owl/extracting-features-from-an-intermediate-layer-of-a-pretrained-model-in-pytorch-c00589bda32b

read for getting a blok output.
https://towardsdatascience.com/everything-you-need-to-know-about-saving-weights-in-pytorch-572651f3f8de

this might help me
https://stackoverflow.com/questions/63427771/extracting-intermediate-layer-outputs-of-a-cnn-in-pytorch

torchextractor might help in feature extraction.
https://github.com/antoinebrl/torchextractor.git


findings :

module subclassing.


model.summary
https://medium.com/the-owl/extracting-features-from-an-intermediate-layer-of-a-pretrained-model-in-pytorch-c00589bda32b

https://towardsdatascience.com/recommending-similar-images-using-pytorch-da019282770c


for pytorch hooks
https://blog.paperspace.com/pytorch-hooks-gradient-clipping-debugging/



In [1]:
import torch
import torchvision.models as models
resnet18 = models.resnet18()


In [2]:
dir(resnet18)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_buffers',
 '_call_impl',
 '_forward_hooks',
 '_forward_impl',
 '_forward_pre_hooks',
 '_get_backward_hooks',
 '_get_name',
 '_is_full_backward_hook',
 '_load_from_state_dict',
 '_load_state_dict_pre_hooks',
 '_make_layer',
 '_maybe_warn_non_full_backward_hook',
 '_modules',
 '_named_members',
 '_non_persistent_buffers_set',
 '_norm_layer',
 '_parameters',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_replicate_for_data_parallel',
 '_save_to_state_dict',
 '_slow_forward',
 '_state_d

In [6]:
import numpy as np
from torchvision import transforms
from PIL import Image

def image_loader(loader, image_name):
    image = Image.open(image_name)
    image = loader(image).float()
    image = torch.tensor(image, requires_grad=True)
    image = image.unsqueeze(0)
    return image

data_transforms = transforms.Compose([
    transforms.Resize(440),
    transforms.CenterCrop(416),
    transforms.ToTensor()
])


model_ft = models.resnet18(pretrained=True)
model_ft.eval()
FILENAME="/content/pexels-dzenina-lukac-1583884.jpg"
print( np.argmax(model_ft(image_loader(data_transforms, FILENAME)).detach().numpy()))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)


809


In [7]:
model_ft(image_loader(data_transforms, FILENAME))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


tensor([[ 7.3491e-01,  2.7160e+00,  7.9677e-01, -8.2283e-01,  1.6049e+00,
          1.7790e+00, -4.7164e-01,  4.2707e-01,  9.5064e-01, -8.9202e-01,
         -2.5634e-01, -1.6432e+00,  3.2216e-01,  6.8254e-01,  1.1927e-01,
          4.1155e-02,  9.3419e-01,  7.9108e-01,  8.2697e-01,  1.3626e+00,
         -3.6341e-01, -8.1614e-01, -2.1467e+00, -3.0721e-02, -2.4887e+00,
         -2.6393e-01,  3.4347e+00,  1.8787e+00,  1.1364e+00,  5.0717e+00,
         -7.9001e-01,  5.9446e-01,  9.0946e-01,  1.6798e+00,  1.1652e+00,
          1.3570e+00,  2.1304e+00,  1.1955e+00,  1.9301e+00,  3.1919e-01,
          2.1331e+00,  2.6146e-01,  2.3447e+00,  1.6853e+00,  1.1560e+00,
          8.6508e-01,  1.4410e+00,  9.7460e-01, -1.6531e+00, -7.9070e-01,
          4.6521e-01,  7.1298e-01,  2.6040e+00,  3.4371e-04,  1.2697e+00,
         -1.0296e-01,  2.4206e+00, -4.9466e-01,  2.7146e+00,  6.4679e-01,
          1.1320e+00,  1.2463e+00,  5.4707e-01,  2.0054e+00,  1.7773e+00,
          4.1954e-01,  2.7912e+00,  2.

In [8]:
c = model_ft.layer1(image_loader(data_transforms, FILENAME)).detach().numpy()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


RuntimeError: ignored

In [ ]:
c

In [9]:
print(resnet18.state_dict)

<bound method Module.state_dict of ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)


In [10]:
# class MyResNet18(resnet18):

#   def __init__(self, *args, **kwargs):
#     super().__init__(*args, **kwargs)

#   def forward(self, xb):
#     x = self.maxpool(self.relu(self.bn1(self.conv1(xb))))
#     x = self.layer1(x)
#     x2 = x = self.layer2(x)
#     x3 = x = self.layer3(x)
#     x4 = x = self.layer4(x)
#     return [x2, x3, x4]

In [11]:
# resnet18.register_forward_hook()

In [12]:
from torchsummary import summary
summary(resnet18,input_size=(3, 416, 416))



----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1         [-1, 64, 208, 208]           9,408
       BatchNorm2d-2         [-1, 64, 208, 208]             128
              ReLU-3         [-1, 64, 208, 208]               0
         MaxPool2d-4         [-1, 64, 104, 104]               0
            Conv2d-5         [-1, 64, 104, 104]          36,864
       BatchNorm2d-6         [-1, 64, 104, 104]             128
              ReLU-7         [-1, 64, 104, 104]               0
            Conv2d-8         [-1, 64, 104, 104]          36,864
       BatchNorm2d-9         [-1, 64, 104, 104]             128
             ReLU-10         [-1, 64, 104, 104]               0
       BasicBlock-11         [-1, 64, 104, 104]               0
           Conv2d-12         [-1, 64, 104, 104]          36,864
      BatchNorm2d-13         [-1, 64, 104, 104]             128
             ReLU-14         [-1, 64, 1

In [13]:
#

# my stategy 
first load resnet 18 model pretrained=true and include top=false

> now create a hooks for extracting feature now need to create multiple hooks
as we are going to get multiple layers feature vector,
once feature vector are collected we will think about rest of part


In [14]:
dir(resnet18)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_buffers',
 '_call_impl',
 '_forward_hooks',
 '_forward_impl',
 '_forward_pre_hooks',
 '_get_backward_hooks',
 '_get_name',
 '_is_full_backward_hook',
 '_load_from_state_dict',
 '_load_state_dict_pre_hooks',
 '_make_layer',
 '_maybe_warn_non_full_backward_hook',
 '_modules',
 '_named_members',
 '_non_persistent_buffers_set',
 '_norm_layer',
 '_parameters',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_replicate_for_data_parallel',
 '_save_to_state_dict',
 '_slow_forward',
 '_state_d

In [15]:
net = models.resnet18(pretrained=True)

In [17]:
class ReductionResNet():
    def __init__(self):
        pass
    
    def forward(self):
        pass


# performming feature extraction using torchextractor package

!pip install git+https://github.com/antoinebrl/torchextractor.git 

In [19]:
!pip install git+https://github.com/antoinebrl/torchextractor.git 

  Cloning https://github.com/antoinebrl/torchextractor.git to /tmp/pip-req-build-uyebs0m6
  Running command git clone -q https://github.com/antoinebrl/torchextractor.git /tmp/pip-req-build-uyebs0m6
  Created wheel for torchextractor: filename=torchextractor-0.3.0-py3-none-any.whl size=10701 sha256=773ea0cf9d26aec68e54b258ba2d77cfb427c50e6d5fd38f80cdebbfc816cd7d
  Stored in directory: /tmp/pip-ephem-wheel-cache-v5of5w5s/wheels/2c/49/d6/f6c15485117e7367197186707bedb9798fad079091debfadef
Successfully built torchextractor


In [20]:
import torch
import torchvision
import torchextractor as tx

model = torchvision.models.resnet18(pretrained=True)
model = tx.Extractor(model, ["layer1", "layer2", "layer3", "layer4"])
# dummy_input = torch.rand(7, 3, 416, 416)
# model_output, features = model(dummy_input)
# feature_shapes = {name: f.shape for name, f in features.items()}
# print(feature_shapes)


In [21]:
model_output, features = model(image_loader(data_transforms, FILENAME))
feature_shapes = {name: f.shape for name, f in features.items()}
feature_shapes

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


{'layer1': torch.Size([1, 64, 104, 104]),
 'layer2': torch.Size([1, 128, 52, 52]),
 'layer3': torch.Size([1, 256, 26, 26]),
 'layer4': torch.Size([1, 512, 13, 13])}

In [22]:
layer1 = features.get('layer1')
layer2 = features.get('layer2')
layer3 = features.get('layer3')
layer4 = features.get('layer4')

layer1.shape, layer2.shape, layer3.shape, layer4.shape

(torch.Size([1, 64, 104, 104]),
 torch.Size([1, 128, 52, 52]),
 torch.Size([1, 256, 26, 26]),
 torch.Size([1, 512, 13, 13]))

In [23]:
# IGNORE: the step is needed but done in a wrong way.
l1 = torch.repeat_interleave(layer1, 8, dim=1)
l2 = torch.repeat_interleave(layer2, 4, dim=1)
l3 = torch.repeat_interleave(layer3, 2, dim=1)
l4 = layer4
l1.shape, l2.shape, l3.shape, l4.shape,

(torch.Size([1, 512, 104, 104]),
 torch.Size([1, 512, 52, 52]),
 torch.Size([1, 512, 26, 26]),
 torch.Size([1, 512, 13, 13]))

In [24]:
# reduction operation reducing size 4d tensor to 1d tensor
aap = torch.nn.AdaptiveAvgPool2d(output_size=(1, 1))

l1aap = aap(layer1)
l2aap = aap(layer2)
l3aap = aap(layer3)
l4aap = aap(layer4)

print(l1aap.shape, l2aap.shape, l3aap.shape, l4aap.shape)


torch.Size([1, 64, 1, 1]) torch.Size([1, 128, 1, 1]) torch.Size([1, 256, 1, 1]) torch.Size([1, 512, 1, 1])


In [26]:
lf = l1aap.reshape([-1])
lf = lf.repeat_interleave(8)
lf.shape

torch.Size([512])

In [47]:
# IMPORTANT: the block works as needed in the  model, don't DELETE

adaptive_avg_pool_2d = torch.nn.AdaptiveAvgPool2d(output_size=(1, 1))

l1 = adaptive_avg_pool_2d(layer1).reshape([-1]).repeat_interleave(8).unsqueeze(0)
l2 = adaptive_avg_pool_2d(layer2).reshape([-1]).repeat_interleave(4).unsqueeze(0)
l3 = adaptive_avg_pool_2d(layer3).reshape([-1]).repeat_interleave(2).unsqueeze(0)
l4 = adaptive_avg_pool_2d(layer4).reshape([-1]).repeat_interleave(1).unsqueeze(0)



In [54]:
embedding = torch.cat((l1,l2,l3,l4), 0).mean(0)
embedding.shape

torch.Size([512])

In [35]:
#  Not working
# intermediate_embedding = torch.cat(l1,l2,l3,l4)
# intermediate_embedding
ll1 = l1.unsqueeze(0)
ll1, l1

(tensor([[0.3472, 0.3472, 0.3472, 0.3472, 0.3472, 0.3472, 0.3472, 0.3472, 0.4069,
          0.4069, 0.4069, 0.4069, 0.4069, 0.4069, 0.4069, 0.4069, 0.2178, 0.2178,
          0.2178, 0.2178, 0.2178, 0.2178, 0.2178, 0.2178, 0.3109, 0.3109, 0.3109,
          0.3109, 0.3109, 0.3109, 0.3109, 0.3109, 0.5679, 0.5679, 0.5679, 0.5679,
          0.5679, 0.5679, 0.5679, 0.5679, 0.2976, 0.2976, 0.2976, 0.2976, 0.2976,
          0.2976, 0.2976, 0.2976, 0.2942, 0.2942, 0.2942, 0.2942, 0.2942, 0.2942,
          0.2942, 0.2942, 0.2345, 0.2345, 0.2345, 0.2345, 0.2345, 0.2345, 0.2345,
          0.2345, 0.9888, 0.9888, 0.9888, 0.9888, 0.9888, 0.9888, 0.9888, 0.9888,
          0.2144, 0.2144, 0.2144, 0.2144, 0.2144, 0.2144, 0.2144, 0.2144, 0.4910,
          0.4910, 0.4910, 0.4910, 0.4910, 0.4910, 0.4910, 0.4910, 0.7148, 0.7148,
          0.7148, 0.7148, 0.7148, 0.7148, 0.7148, 0.7148, 0.2212, 0.2212, 0.2212,
          0.2212, 0.2212, 0.2212, 0.2212, 0.2212, 0.2197, 0.2197, 0.2197, 0.2197,
          0.2197

In [29]:
#  x = torch.tensor([[1], [2], [3]])
# >>> x.size()
# torch.Size([3, 1])
# >>> x.expand(3, 4)
# tensor([[ 1,  1,  1,  1],
#         [ 2,  2,  2,  2],
#         [ 3,  3,  3,  3]])
# >>> x.expand(-1, 4)   # -1 means not changing the size of that dimension
# tensor([[ 1,  1,  1,  1],
#         [ 2,  2,  2,  2],
#         [ 3,  3,  3,  3]])

In [ ]:
output.shape

In [ ]:
l1rl = torch.repeat_interleave(output, 8, dim=1)
l1rl.shape

In [ ]:
model

In [ ]:
output

In [57]:
cos = torch.nn.CosineSimilarity(dim=0, eps=1e-6)
res = cos(embedding, embedding)
res

tensor(1., grad_fn=<DivBackward0>)